.Dd Mart 16, 2013
.Dt marvin 1
.Os
.Sh NAME
.Nm marvin
.Nd Programm for management system
.Sh DESCRIPTION
The
.Nm
utility for management system based on dynamic modules.
.Sh SEE ALSO
.Xr sysctl 1
.Sh AUTHORS
.An -nosplit
Source by
.An Stanislav Putrya Aq vagner@bsdway.ru
This
manual page was written by
.An Stanislav Putrya Aq vagner@bsdway.ru .
